{{- if .Values.openshiftOIDC.caBundleSync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-oidc.fullname" . }}-keycloak-ca-sync-script
  namespace: {{ .Values.keycloak.namespace }}
  labels:
    {{- include "keycloak-oidc.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  sync_keycloak_ca.py: |-
{{ .Files.Get "files/sync_keycloak_ca.py" | indent 4 }}
{{- end }}
