apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connectionSecret.name }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
type: Opaque
stringData:
  db.host: {{ include "mongo.fullname" . | quote }}
  db.port: {{ .Values.service.port | quote }}
  {{- if .Values.auth.enabled }}
  db.username: {{ .Values.auth.rootUsername | quote }}
  db.password: {{ .Values.auth.rootPassword | quote }}
  db.uri: {{ printf "mongodb://%s:%s@%s:%v/" .Values.auth.rootUsername .Values.auth.rootPassword (include "mongo.fullname" .) .Values.service.port | quote }}
  {{- else }}
  db.username: ""
  db.password: ""
  db.uri: {{ printf "mongodb://%s:%v/" (include "mongo.fullname" .) .Values.service.port | quote }}
  {{- end }}
