apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openshift-mcp-server.serviceAccountName" . }}
  labels:
    {{- include "openshift-mcp-server.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
