---
global:
  pattern: multicloud-gitops
  singleArgoCD: true
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  variant: standalone
  multiSourceConfig:
    enabled: true
    #clusterGroupGitRepoUrl: https://github.com/mbaldessari/clustergroup-chart
    #clusterGroupChartGitRevision: backstage
    clusterGroupChartVersion: "0.9.*"
