apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
spec:
  components:
    dashboard:
      managementState: Managed
    workbenches:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed
    kueue:
      managementState: Managed
    codeflare:
      managementState: Managed
    ray:
      managementState: Managed
    modelmeshserving:
      managementState: Managed
    kserve:
      managementState: Managed
      serving:
        ingressGateway:
          certificate:
            type: OpenshiftDefaultIngress
        managementState: Managed
        name: knative-serving
    trustyai:
      managementState: Managed
      # issue with trustyai being OOMKilled, can be dropped in the next RHOAI release
      devFlags:
        manifests:
        - contextDir: config
          sourcePath: ''
          uri: https://api.github.com/repos/trustyai-explainability/trustyai-service-operator/tarball/main
    modelregistry:
        managementState: Managed
        registriesNamespace: rhoai-model-registries
