apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
  labels:
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/instance: default-dsc
    app.kubernetes.io/part-of: rhods-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rhods-operator
spec:
  components:
    kserve:
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headless
      managementState: Managed
    modelregistry:
      registriesNamespace: rhoai-model-registries
      managementState: Removed
    kueue:
      managementState: Managed
    workbenches:
      workbenchNamespace: rhods-notebooks
      managementState: Managed
    dashboard:
      managementState: Managed
    aipipelines:
      managementState: Managed
    trainer:
      managementState: Managed
    mlflowoperator:
      managementState: Managed
