apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  labels:
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/instance: default-dsc
    app.kubernetes.io/part-of: rhods-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rhods-operator
spec:
  components:
    codeflare:
      managementState: Managed
    kserve:
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headless
      serving:
        ingressGateway:
          certificate:
            type: OpenshiftDefaultIngress
        managementState: Removed
        name: knative-serving
      managementState: Managed
    modelregistry:
      registriesNamespace: rhoai-model-registries
      managementState: Removed
    feastoperator:
      managementState: Removed
    trustyai:
      managementState: Managed
      # # issue with trustyai being OOMKilled, can be dropped in the next RHOAI release
      # devFlags:
      #   manifests:
      #   - contextDir: config
      #     sourcePath: ''
      #     uri: https://api.github.com/repos/trustyai-explainability/trustyai-service-operator/tarball/main
    ray:
      managementState: Managed
    kueue:
      managementState: Managed
    workbenches:
      workbenchNamespace: rhods-notebooks
      managementState: Managed
    dashboard:
      managementState: Managed
    modelmeshserving:
      managementState: Removed
    datasciencepipelines:
      managementState: Managed
    trainingoperator:
      managementState: Managed
    llamastackoperator:
      managementState: Managed
