{{- include "openshift-lightspeed-operator.validate" . -}}
{{- if and .Values.subscription.enabled .Values.installNamespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.installNamespace.name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: openshift-lightspeed-operator
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
{{- end }}
