apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connectionSecret.name }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  db.endpoint: {{ include "redis.fullname" . | quote }}
  db.port: {{ .Values.service.port | quote }}
  {{- if .Values.auth.enabled }}
  db.auth_token: {{ .Values.auth.password | quote }}
  {{- else }}
  db.auth_token: ""
  {{- end }}
